-- Mapeamento de/para: código do fornecedor (cProd da NF-e) → produto do catálogo.
-- Permite o mesmo item físico com códigos diferentes por fornecedor,
-- e reaproveitar o vínculo nas próximas importações de XML.

create table if not exists public.fornecedor_produto_codigos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  fornecedor_id bigint not null references public.fornecedores(id) on delete cascade,
  codigo_fornecedor text not null,
  ean text,
  produto_id bigint not null references public.produto_catalogo(id) on delete cascade,
  descricao_fornecedor text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fornecedor_produto_codigos_codigo_chk check (btrim(codigo_fornecedor) <> '')
);

-- Um código do fornecedor aponta para um único produto na empresa
create unique index if not exists ux_forn_prod_cod_empresa_forn_codigo
  on public.fornecedor_produto_codigos (empresa_id, fornecedor_id, codigo_fornecedor);

create index if not exists idx_forn_prod_cod_empresa_produto
  on public.fornecedor_produto_codigos (empresa_id, produto_id);

create index if not exists idx_forn_prod_cod_empresa_ean
  on public.fornecedor_produto_codigos (empresa_id, ean)
  where ean is not null and btrim(ean) <> '';

alter table public.fornecedor_produto_codigos enable row level security;

drop policy if exists fornecedor_produto_codigos_tenant on public.fornecedor_produto_codigos;
create policy fornecedor_produto_codigos_tenant on public.fornecedor_produto_codigos
  for all using (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  ) with check (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  );

drop policy if exists fornecedor_produto_codigos_platform_admin on public.fornecedor_produto_codigos;
create policy fornecedor_produto_codigos_platform_admin on public.fornecedor_produto_codigos
  for all using (public.is_platform_admin()) with check (public.is_platform_admin());

grant select, insert, update, delete on public.fornecedor_produto_codigos to authenticated;
grant usage, select on sequence public.fornecedor_produto_codigos_id_seq to authenticated;

comment on table public.fornecedor_produto_codigos is
  'De/para: codigo do item no fornecedor (cProd NF-e) para produto do catalogo da empresa.';
