-- Modulo de estoque: movimentos, parametros e RPC de registro atomico.

alter table public.produto_catalogo
  add column if not exists estoque_maximo integer,
  add column if not exists lead_time_dias integer default 7,
  add column if not exists classe_abc text,
  add column if not exists classe_abc_atualizado_em timestamptz;

update public.produto_catalogo
set estoque_atual = coalesce(estoque_atual, 0)
where estoque_atual is null;

update public.produto_catalogo
set estoque_minimo = coalesce(estoque_minimo, 0)
where estoque_minimo is null;

comment on column public.produto_catalogo.estoque_maximo is
  'Teto de reposição (opcional). Usado para sugerir quantidade de compra.';
comment on column public.produto_catalogo.lead_time_dias is
  'Prazo medio de reposicao em dias (padrao 7).';
comment on column public.produto_catalogo.classe_abc is
  'Classificacao ABC (A/B/C) calculada pelo consumo/faturamento.';
comment on column public.produto_catalogo.classe_abc_atualizado_em is
  'Ultima atualizacao da classificacao ABC.';

create table if not exists public.estoque_movimentos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  produto_id bigint not null references public.produto_catalogo(id) on delete cascade,
  tipo text not null,
  quantidade numeric(14,3) not null,
  saldo_anterior numeric(14,3) not null,
  saldo_posterior numeric(14,3) not null,
  custo_unitario numeric(14,4),
  motivo text,
  observacoes text,
  documento_id bigint references public.documentos_venda(id) on delete set null,
  documento_item_id bigint,
  usuario_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint estoque_movimentos_tipo_check check (
    tipo = any (array[
      'entrada'::text,
      'saida'::text,
      'ajuste'::text,
      'venda'::text,
      'estorno_venda'::text,
      'inventario'::text
    ])
  ),
  constraint estoque_movimentos_quantidade_check check (quantidade <> 0)
);

create index if not exists idx_estoque_movimentos_empresa_created
  on public.estoque_movimentos (empresa_id, created_at desc);

create index if not exists idx_estoque_movimentos_produto_created
  on public.estoque_movimentos (empresa_id, produto_id, created_at desc);

create index if not exists idx_estoque_movimentos_documento
  on public.estoque_movimentos (empresa_id, documento_id)
  where documento_id is not null;

create index if not exists idx_estoque_movimentos_tipo
  on public.estoque_movimentos (empresa_id, tipo, created_at desc);

alter table public.estoque_movimentos enable row level security;

drop policy if exists estoque_movimentos_tenant on public.estoque_movimentos;
create policy estoque_movimentos_tenant on public.estoque_movimentos
  for all
  using (
    public.user_belongs_to_empresa(empresa_id)
    or public.is_platform_admin()
  )
  with check (
    public.user_belongs_to_empresa(empresa_id)
    or public.is_platform_admin()
  );

drop policy if exists estoque_movimentos_platform_admin on public.estoque_movimentos;
create policy estoque_movimentos_platform_admin on public.estoque_movimentos
  for all
  using (public.is_platform_admin())
  with check (public.is_platform_admin());

grant select, insert, update, delete on public.estoque_movimentos to authenticated;
grant usage, select on sequence public.estoque_movimentos_id_seq to authenticated;

-- Registro atomico de movimento + atualizacao de saldo.
create or replace function public.registrar_estoque_movimento(
  p_empresa_id uuid,
  p_produto_id bigint,
  p_tipo text,
  p_quantidade numeric,
  p_motivo text default null,
  p_observacoes text default null,
  p_documento_id bigint default null,
  p_documento_item_id bigint default null,
  p_custo_unitario numeric default null,
  p_permitir_negativo boolean default false,
  p_metadata jsonb default '{}'::jsonb
)
returns public.estoque_movimentos
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prod record;
  v_saldo_ant numeric(14,3);
  v_delta numeric(14,3);
  v_saldo_pos numeric(14,3);
  v_qtd_signed numeric(14,3);
  v_tipo text;
  v_row public.estoque_movimentos;
  v_custo numeric(14,4);
begin
  if p_empresa_id is null then
    raise exception 'empresa_id obrigatorio';
  end if;

  if not public.user_belongs_to_empresa(p_empresa_id) and not public.is_platform_admin() then
    raise exception 'Acesso negado';
  end if;

  v_tipo := lower(trim(coalesce(p_tipo, '')));
  if v_tipo not in ('entrada', 'saida', 'ajuste', 'venda', 'estorno_venda', 'inventario') then
    raise exception 'Tipo de movimento invalido: %', p_tipo;
  end if;

  if p_quantidade is null then
    raise exception 'Quantidade obrigatoria';
  end if;

  select
    p.id,
    p.nome,
    coalesce(p.estoque_atual, 0)::numeric as estoque_atual,
    coalesce(p.controla_estoque, true) as controla_estoque,
    p.custo
  into v_prod
  from public.produto_catalogo p
  where p.id = p_produto_id
    and p.empresa_id = p_empresa_id
  for update;

  if not found then
    raise exception 'Produto nao encontrado';
  end if;

  if not v_prod.controla_estoque then
    raise exception 'Produto "%" nao controla estoque', v_prod.nome;
  end if;

  v_saldo_ant := v_prod.estoque_atual;
  v_custo := coalesce(p_custo_unitario, v_prod.custo);

  if v_tipo in ('entrada', 'estorno_venda') then
    if p_quantidade <= 0 then
      raise exception 'Quantidade de entrada deve ser positiva';
    end if;
    v_delta := p_quantidade;
  elsif v_tipo in ('saida', 'venda') then
    if p_quantidade <= 0 then
      raise exception 'Quantidade de saida deve ser positiva';
    end if;
    v_delta := -p_quantidade;
  elsif v_tipo in ('ajuste', 'inventario') then
    -- p_quantidade = novo saldo absoluto
    if p_quantidade < 0 and not p_permitir_negativo then
      raise exception 'Saldo de ajuste nao pode ser negativo';
    end if;
    v_delta := p_quantidade - v_saldo_ant;
    if v_delta = 0 then
      raise exception 'Ajuste sem alteracao de saldo';
    end if;
  end if;

  v_saldo_pos := v_saldo_ant + v_delta;
  v_qtd_signed := v_delta;

  if v_saldo_pos < 0 and not coalesce(p_permitir_negativo, false) then
    raise exception
      'Estoque insuficiente para "%". Saldo atual: %, necessario: %',
      v_prod.nome,
      v_saldo_ant,
      abs(v_delta);
  end if;

  update public.produto_catalogo
  set
    estoque_atual = round(v_saldo_pos)::integer,
    updated_at = now()
  where id = p_produto_id
    and empresa_id = p_empresa_id;

  insert into public.estoque_movimentos (
    empresa_id,
    produto_id,
    tipo,
    quantidade,
    saldo_anterior,
    saldo_posterior,
    custo_unitario,
    motivo,
    observacoes,
    documento_id,
    documento_item_id,
    usuario_id,
    metadata
  ) values (
    p_empresa_id,
    p_produto_id,
    v_tipo,
    v_qtd_signed,
    v_saldo_ant,
    round(v_saldo_pos)::numeric,
    v_custo,
    nullif(trim(coalesce(p_motivo, '')), ''),
    nullif(trim(coalesce(p_observacoes, '')), ''),
    p_documento_id,
    p_documento_item_id,
    auth.uid(),
    coalesce(p_metadata, '{}'::jsonb)
  )
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.registrar_estoque_movimento(
  uuid, bigint, text, numeric, text, text, bigint, bigint, numeric, boolean, jsonb
) from public;

grant execute on function public.registrar_estoque_movimento(
  uuid, bigint, text, numeric, text, text, bigint, bigint, numeric, boolean, jsonb
) to authenticated;

comment on table public.estoque_movimentos is
  'Historico de entradas, saidas, ajustes, vendas e estornos de estoque.';
comment on function public.registrar_estoque_movimento is
  'Registra movimento de estoque e atualiza produto_catalogo.estoque_atual de forma atomica.';
