-- Calendário de funcionamento: horários padrão + feriados/fechamentos.

create table if not exists public.calendario_horarios (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  dia_semana smallint not null,
  aberto boolean not null default true,
  hora_inicio time,
  hora_fim time,
  hora_inicio_tarde time,
  hora_fim_tarde time,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calendario_horarios_dia_check check (dia_semana between 0 and 6),
  constraint calendario_horarios_empresa_dia_key unique (empresa_id, dia_semana)
);

comment on table public.calendario_horarios is
  'Horário padrão de funcionamento por dia da semana (0=domingo ... 6=sábado).';
comment on column public.calendario_horarios.hora_inicio is 'Início do turno principal (manhã/único).';
comment on column public.calendario_horarios.hora_fim is 'Fim do turno principal.';
comment on column public.calendario_horarios.hora_inicio_tarde is 'Início do 2º turno (opcional).';
comment on column public.calendario_horarios.hora_fim_tarde is 'Fim do 2º turno (opcional).';

create index if not exists idx_calendario_horarios_empresa
  on public.calendario_horarios (empresa_id);

alter table public.calendario_horarios enable row level security;

drop policy if exists calendario_horarios_tenant on public.calendario_horarios;
create policy calendario_horarios_tenant on public.calendario_horarios
  for all using (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  ) with check (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  );

drop policy if exists calendario_horarios_platform_admin on public.calendario_horarios;
create policy calendario_horarios_platform_admin on public.calendario_horarios
  for all using (public.is_platform_admin()) with check (public.is_platform_admin());

grant select, insert, update, delete on public.calendario_horarios to authenticated;
grant usage, select on sequence public.calendario_horarios_id_seq to authenticated;

create table if not exists public.calendario_feriados (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  data date not null,
  nome text not null,
  tipo text not null default 'feriado',
  fecha_dia_todo boolean not null default true,
  hora_inicio time,
  hora_fim time,
  recorrente boolean not null default false,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calendario_feriados_tipo_check check (
    tipo = any (array['feriado'::text, 'recesso'::text, 'folga'::text, 'outro'::text])
  )
);

comment on table public.calendario_feriados is
  'Dias de fechamento (feriados, recesso, folga). Se recorrente=true, repete todo ano (mesmo dia/mês).';

create index if not exists idx_calendario_feriados_empresa_data
  on public.calendario_feriados (empresa_id, data);

create unique index if not exists ux_calendario_feriados_empresa_data_nome
  on public.calendario_feriados (empresa_id, data, nome);

alter table public.calendario_feriados enable row level security;

drop policy if exists calendario_feriados_tenant on public.calendario_feriados;
create policy calendario_feriados_tenant on public.calendario_feriados
  for all using (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  ) with check (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  );

drop policy if exists calendario_feriados_platform_admin on public.calendario_feriados;
create policy calendario_feriados_platform_admin on public.calendario_feriados
  for all using (public.is_platform_admin()) with check (public.is_platform_admin());

grant select, insert, update, delete on public.calendario_feriados to authenticated;
grant usage, select on sequence public.calendario_feriados_id_seq to authenticated;
