-- Modulo de Compras: fornecedores, notas de entrada, itens e contas a pagar.

-- ========== FORNECEDORES ==========
create table if not exists public.fornecedores (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  nome text not null,
  documento text,
  telefone text,
  email text,
  endereco text,
  cidade text,
  uf text,
  observacoes text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_fornecedores_empresa_nome
  on public.fornecedores (empresa_id, nome);

create unique index if not exists ux_fornecedores_empresa_documento
  on public.fornecedores (empresa_id, documento)
  where documento is not null and btrim(documento) <> '';

alter table public.fornecedores enable row level security;

drop policy if exists fornecedores_tenant on public.fornecedores;
create policy fornecedores_tenant on public.fornecedores
  for all using (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  ) with check (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  );

drop policy if exists fornecedores_platform_admin on public.fornecedores;
create policy fornecedores_platform_admin on public.fornecedores
  for all using (public.is_platform_admin()) with check (public.is_platform_admin());

grant select, insert, update, delete on public.fornecedores to authenticated;
grant usage, select on sequence public.fornecedores_id_seq to authenticated;

-- ========== NOTAS DE ENTRADA ==========
create table if not exists public.notas_entrada (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  fornecedor_id bigint references public.fornecedores(id) on delete set null,
  numero_nf text,
  serie text,
  chave_acesso text,
  data_emissao date,
  data_entrada date not null default current_date,
  status text not null default 'rascunho',
  valor_produtos numeric(14,2) not null default 0,
  valor_desconto numeric(14,2) not null default 0,
  valor_frete numeric(14,2) not null default 0,
  valor_outras numeric(14,2) not null default 0,
  valor_total numeric(14,2) not null default 0,
  observacoes text,
  parcelas integer not null default 1,
  vencimento_primeira date,
  intervalo_dias integer not null default 30,
  forma_pagamento_id bigint references public.formas_pagamento(id) on delete set null,
  estoque_aplicado boolean not null default false,
  financeiro_aplicado boolean not null default false,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notas_entrada_status_check check (
    status = any (array['rascunho'::text, 'lancada'::text, 'cancelada'::text])
  )
);

create index if not exists idx_notas_entrada_empresa_data
  on public.notas_entrada (empresa_id, data_entrada desc);

create index if not exists idx_notas_entrada_fornecedor
  on public.notas_entrada (empresa_id, fornecedor_id);

create index if not exists idx_notas_entrada_status
  on public.notas_entrada (empresa_id, status);

alter table public.notas_entrada enable row level security;

drop policy if exists notas_entrada_tenant on public.notas_entrada;
create policy notas_entrada_tenant on public.notas_entrada
  for all using (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  ) with check (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  );

drop policy if exists notas_entrada_platform_admin on public.notas_entrada;
create policy notas_entrada_platform_admin on public.notas_entrada
  for all using (public.is_platform_admin()) with check (public.is_platform_admin());

grant select, insert, update, delete on public.notas_entrada to authenticated;
grant usage, select on sequence public.notas_entrada_id_seq to authenticated;

-- ========== ITENS DA NOTA ==========
create table if not exists public.notas_entrada_itens (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  nota_id bigint not null references public.notas_entrada(id) on delete cascade,
  produto_id bigint references public.produto_catalogo(id) on delete set null,
  descricao text,
  quantidade numeric(14,3) not null default 1,
  valor_unitario numeric(14,4) not null default 0,
  valor_total numeric(14,2) not null default 0,
  atualiza_custo boolean not null default true,
  atualiza_estoque boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_notas_entrada_itens_nota
  on public.notas_entrada_itens (empresa_id, nota_id);

alter table public.notas_entrada_itens enable row level security;

drop policy if exists notas_entrada_itens_tenant on public.notas_entrada_itens;
create policy notas_entrada_itens_tenant on public.notas_entrada_itens
  for all using (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  ) with check (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  );

drop policy if exists notas_entrada_itens_platform_admin on public.notas_entrada_itens;
create policy notas_entrada_itens_platform_admin on public.notas_entrada_itens
  for all using (public.is_platform_admin()) with check (public.is_platform_admin());

grant select, insert, update, delete on public.notas_entrada_itens to authenticated;
grant usage, select on sequence public.notas_entrada_itens_id_seq to authenticated;

-- ========== CONTAS A PAGAR ==========
create table if not exists public.contas_pagar (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  nota_entrada_id bigint references public.notas_entrada(id) on delete set null,
  fornecedor_id bigint references public.fornecedores(id) on delete set null,
  origem text not null default 'nota_entrada',
  numero_titulo text,
  emissao timestamptz not null default now(),
  valor_original numeric(14,2) not null default 0,
  valor_aberto numeric(14,2) not null default 0,
  status text not null default 'aberto',
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contas_pagar_status_check check (
    status = any (array['aberto'::text, 'parcial'::text, 'pago'::text, 'cancelado'::text])
  )
);

create index if not exists idx_contas_pagar_empresa
  on public.contas_pagar (empresa_id, status, emissao desc);

create index if not exists idx_contas_pagar_nota
  on public.contas_pagar (empresa_id, nota_entrada_id);

alter table public.contas_pagar enable row level security;

drop policy if exists contas_pagar_tenant on public.contas_pagar;
create policy contas_pagar_tenant on public.contas_pagar
  for all using (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  ) with check (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  );

drop policy if exists contas_pagar_platform_admin on public.contas_pagar;
create policy contas_pagar_platform_admin on public.contas_pagar
  for all using (public.is_platform_admin()) with check (public.is_platform_admin());

grant select, insert, update, delete on public.contas_pagar to authenticated;
grant usage, select on sequence public.contas_pagar_id_seq to authenticated;

-- ========== PARCELAS A PAGAR ==========
create table if not exists public.contas_pagar_parcelas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  conta_pagar_id bigint not null references public.contas_pagar(id) on delete cascade,
  numero_parcela integer not null default 1,
  vencimento date,
  valor_parcela numeric(14,2) not null default 0,
  valor_pago numeric(14,2) not null default 0,
  status text not null default 'pendente',
  forma_pagamento_id bigint references public.formas_pagamento(id) on delete set null,
  observacoes text,
  created_at timestamptz not null default now(),
  constraint contas_pagar_parcelas_status_check check (
    status = any (array['pendente'::text, 'pago'::text, 'parcial'::text, 'cancelado'::text])
  )
);

create index if not exists idx_contas_pagar_parcelas_conta
  on public.contas_pagar_parcelas (empresa_id, conta_pagar_id);

create index if not exists idx_contas_pagar_parcelas_venc
  on public.contas_pagar_parcelas (empresa_id, vencimento, status);

alter table public.contas_pagar_parcelas enable row level security;

drop policy if exists contas_pagar_parcelas_tenant on public.contas_pagar_parcelas;
create policy contas_pagar_parcelas_tenant on public.contas_pagar_parcelas
  for all using (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  ) with check (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  );

drop policy if exists contas_pagar_parcelas_platform_admin on public.contas_pagar_parcelas;
create policy contas_pagar_parcelas_platform_admin on public.contas_pagar_parcelas
  for all using (public.is_platform_admin()) with check (public.is_platform_admin());

grant select, insert, update, delete on public.contas_pagar_parcelas to authenticated;
grant usage, select on sequence public.contas_pagar_parcelas_id_seq to authenticated;

-- ========== PAGAMENTOS (baixa) ==========
create table if not exists public.pagamentos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  parcela_id bigint not null references public.contas_pagar_parcelas(id) on delete cascade,
  data_pagamento date not null default current_date,
  valor numeric(14,2) not null,
  forma_pagamento_id bigint references public.formas_pagamento(id) on delete set null,
  observacoes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_pagamentos_parcela
  on public.pagamentos (empresa_id, parcela_id);

alter table public.pagamentos enable row level security;

drop policy if exists pagamentos_tenant on public.pagamentos;
create policy pagamentos_tenant on public.pagamentos
  for all using (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  ) with check (
    public.user_belongs_to_empresa(empresa_id) or public.is_platform_admin()
  );

drop policy if exists pagamentos_platform_admin on public.pagamentos;
create policy pagamentos_platform_admin on public.pagamentos
  for all using (public.is_platform_admin()) with check (public.is_platform_admin());

grant select, insert, update, delete on public.pagamentos to authenticated;
grant usage, select on sequence public.pagamentos_id_seq to authenticated;

comment on table public.fornecedores is 'Cadastro de fornecedores para compras e contas a pagar.';
comment on table public.notas_entrada is 'Notas fiscais / entradas de compra.';
comment on table public.notas_entrada_itens is 'Itens da nota de entrada; podem gerar estoque e atualizar custo.';
comment on table public.contas_pagar is 'Titulos a pagar gerados por notas de entrada ou manuais.';
comment on table public.contas_pagar_parcelas is 'Parcelas dos titulos a pagar.';
comment on table public.pagamentos is 'Historico de baixas/pagamentos de parcelas a pagar.';
