-- GuPedal SaaS multiempresa
-- Todas as tabelas de negocio possuem empresa_id.

create extension if not exists pgcrypto;

create table if not exists public.empresas (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.usuarios_empresas (
  user_id uuid not null references auth.users(id) on delete cascade,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  role text not null default 'owner',
  ativo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  primary key (user_id, empresa_id)
);

create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamp with time zone not null default now()
);

create or replace function public.user_belongs_to_empresa(target_empresa_id uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.usuarios_empresas ue
    where ue.user_id = auth.uid()
      and ue.empresa_id = target_empresa_id
      and ue.ativo = true
  );
$$;

create or replace function public.is_platform_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.platform_admins pa
    where pa.user_id = auth.uid()
  );
$$;

create or replace function public.admin_find_user_by_email(target_email text)
returns table(user_id uuid, email text)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'Acesso negado';
  end if;

  return query
  select u.id, u.email::text
  from auth.users u
  where lower(u.email::text) = lower(target_email)
  limit 1;
end;
$$;

revoke all on function public.admin_find_user_by_email(text) from public;
grant execute on function public.admin_find_user_by_email(text) to authenticated;

create or replace function public.current_empresa_id()
returns uuid
language sql
stable
as $$
  select ue.empresa_id
  from public.usuarios_empresas ue
  where ue.user_id = auth.uid()
    and ue.ativo = true
  order by ue.created_at asc
  limit 1;
$$;

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id),
  nome text not null,
  telefone text,
  email text,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id),
  nome text not null,
  preco numeric(12,2) not null default 0,
  estoque integer not null default 0,
  ponto_pedido integer not null default 0,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id),
  cliente_id bigint references public.clientes(id),
  data_pedido timestamp with time zone not null default now(),
  status text not null default 'aberto',
  descricao text,
  valor_total numeric(12,2) not null default 0,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.pedido_itens (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id),
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  produto_id bigint not null references public.produtos(id),
  quantidade integer not null check (quantidade > 0),
  valor_unitario numeric(12,2) not null check (valor_unitario >= 0),
  desconto numeric(12,2) not null default 0 check (desconto >= 0),
  total numeric(12,2) not null default 0,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.orcamentos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id),
  cliente_id bigint references public.clientes(id),
  data_orcamento timestamp with time zone not null default now(),
  status text not null default 'aberto',
  descricao text,
  valor_total numeric(12,2) not null default 0,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.orcamento_itens (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id),
  orcamento_id bigint not null references public.orcamentos(id) on delete cascade,
  produto_id bigint not null references public.produtos(id),
  quantidade integer not null check (quantidade > 0),
  valor_unitario numeric(12,2) not null check (valor_unitario >= 0),
  desconto numeric(12,2) not null default 0 check (desconto >= 0),
  total numeric(12,2) not null default 0,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.despesas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id),
  data_despesa timestamp with time zone not null default now(),
  descricao text not null,
  categoria text,
  status text not null default 'aberto',
  valor numeric(12,2) not null check (valor >= 0),
  created_at timestamp with time zone not null default now()
);

alter table public.empresas enable row level security;
alter table public.usuarios_empresas enable row level security;
alter table public.platform_admins enable row level security;
alter table public.clientes enable row level security;
alter table public.produtos enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_itens enable row level security;
alter table public.orcamentos enable row level security;
alter table public.orcamento_itens enable row level security;
alter table public.despesas enable row level security;

drop policy if exists "usuarios_empresas_select" on public.usuarios_empresas;
create policy "usuarios_empresas_select"
on public.usuarios_empresas
for select
using (user_id = auth.uid());

drop policy if exists "usuarios_empresas_tenant_read" on public.usuarios_empresas;
create policy "usuarios_empresas_tenant_read"
on public.usuarios_empresas
for select
using (public.user_belongs_to_empresa(empresa_id));

drop policy if exists "usuarios_empresas_platform_admin" on public.usuarios_empresas;
create policy "usuarios_empresas_platform_admin"
on public.usuarios_empresas
for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "platform_admins_self" on public.platform_admins;
create policy "platform_admins_self"
on public.platform_admins
for select
using (user_id = auth.uid());

drop policy if exists "empresas_select" on public.empresas;
create policy "empresas_select"
on public.empresas
for select
using (public.user_belongs_to_empresa(id));

drop policy if exists "empresas_platform_admin" on public.empresas;
create policy "empresas_platform_admin"
on public.empresas
for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "clientes_tenant" on public.clientes;
create policy "clientes_tenant"
on public.clientes
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists "produtos_tenant" on public.produtos;
create policy "produtos_tenant"
on public.produtos
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists "pedidos_tenant" on public.pedidos;
create policy "pedidos_tenant"
on public.pedidos
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists "pedido_itens_tenant" on public.pedido_itens;
create policy "pedido_itens_tenant"
on public.pedido_itens
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists "orcamentos_tenant" on public.orcamentos;
create policy "orcamentos_tenant"
on public.orcamentos
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists "orcamento_itens_tenant" on public.orcamento_itens;
create policy "orcamento_itens_tenant"
on public.orcamento_itens
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists "despesas_tenant" on public.despesas;
create policy "despesas_tenant"
on public.despesas
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

-- Seed de exemplo para onboarding (ajuste nomes e emails).
-- 1) criar empresa
-- insert into public.empresas (nome) values ('Empresa Demo') returning id;
-- 2) criar usuario no Auth (Dashboard Supabase)
-- 3) vincular usuario na empresa
-- insert into public.usuarios_empresas (user_id, empresa_id, role)
-- values ('UUID_DO_AUTH_USER', 'UUID_DA_EMPRESA', 'owner');
-- 4) promover administrador da plataforma
-- insert into public.platform_admins (user_id)
-- values ('UUID_DO_AUTH_USER')
-- on conflict (user_id) do nothing;
