-- Arquitetura V2 de vendas e financeiro para SaaS multi-tenant
-- Objetivo: separar faturamento de fluxo de caixa e suportar pagamentos parcelados.

-- =====================
-- Funcoes auxiliares
-- =====================

create or replace function public.parse_datetime_br(value_text text)
returns timestamptz
language sql
immutable
as $$
  select case
    when value_text is null or btrim(value_text) = '' then null
    else to_timestamp(btrim(value_text), 'DD/MM/YYYY HH24:MI:SS')
  end;
$$;

create or replace function public.parse_numeric_br(value_text text)
returns numeric
language sql
immutable
as $$
  select case
    when value_text is null or btrim(value_text) = '' then null
    else nullif(
      replace(
        replace(
          replace(
            regexp_replace(value_text, '[^0-9,.-]', '', 'g'),
            '.',
            ''
          ),
          ',',
          '.'
        ),
        ' ',
        ''
      ),
      ''
    )::numeric
  end;
$$;

create or replace function public.parse_percent_numeric_br(value_text text)
returns numeric
language sql
immutable
as $$
  select case
    when value_text is null or btrim(value_text) = '' then null
    else nullif(
      replace(
        replace(regexp_replace(value_text, '[^0-9,.-]', '', 'g'), '.', ''),
        ',',
        '.'
      ),
      ''
    )::numeric
  end;
$$;

-- =====================
-- Tabelas de staging/raw
-- =====================

create table if not exists public.vendas_import_raw (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id),
  origem text not null default 'google_sheets',
  lote_ref text not null,
  source_row_num integer,
  tipo_venda_raw text,
  pedido_legacy_id_raw text,
  cliente_legacy_id_raw text,
  quantidade_raw text,
  preco_unitario_raw text,
  preco_total_raw text,
  data_venda_raw text,
  custo_unitario_raw text,
  custo_total_raw text,
  margem_pedido_raw text,
  tipo_pgto_raw text,
  marca_raw text,
  modelo_raw text,
  cor_raw text,
  acessorios_raw text,
  descricao_raw text,
  foto_raw text,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_vendas_import_raw_empresa_lote
  on public.vendas_import_raw (empresa_id, lote_ref);

-- =====================
-- Dominio comercial
-- =====================

create table if not exists public.documentos_venda (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id),
  tipo_documento text not null check (tipo_documento in ('pedido', 'orcamento')),
  origem text not null default 'legacy_sheet',
  origem_legacy_id text,
  cliente_id bigint references public.clientes(id),
  cliente_legacy_id text,
  data_emissao timestamptz not null default now(),
  status text not null default 'aberto',
  subtotal numeric(12,2) not null default 0,
  desconto numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  custo_total numeric(12,2),
  margem_percentual numeric(8,2),
  observacoes text,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, tipo_documento, origem_legacy_id)
);

create table if not exists public.documento_venda_itens (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id),
  documento_id bigint not null references public.documentos_venda(id) on delete cascade,
  produto_id bigint references public.produto_catalogo(id),
  descricao_item text,
  marca text,
  modelo text,
  cor text,
  acessorios text,
  foto_ref text,
  quantidade numeric(12,3) not null default 1,
  valor_unitario numeric(12,2) not null default 0,
  valor_total numeric(12,2) not null default 0,
  custo_unitario numeric(12,2),
  custo_total numeric(12,2),
  margem_percentual numeric(8,2),
  raw_payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_documento_venda_itens_doc
  on public.documento_venda_itens (documento_id);

-- =====================
-- Dominio financeiro
-- =====================

create table if not exists public.formas_pagamento (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id),
  nome text not null,
  tipo text not null default 'outro',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (empresa_id, nome)
);

create table if not exists public.contas_receber (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id),
  documento_id bigint references public.documentos_venda(id) on delete set null,
  cliente_id bigint references public.clientes(id),
  origem text not null default 'venda',
  numero_titulo text,
  emissao timestamptz not null default now(),
  valor_original numeric(12,2) not null,
  valor_aberto numeric(12,2) not null,
  status text not null default 'aberto' check (status in ('aberto', 'parcial', 'recebido', 'cancelado')),
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contas_receber_parcelas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id),
  conta_receber_id bigint not null references public.contas_receber(id) on delete cascade,
  numero_parcela integer not null,
  vencimento timestamptz,
  valor_parcela numeric(12,2) not null,
  valor_recebido numeric(12,2) not null default 0,
  status text not null default 'pendente' check (status in ('pendente', 'parcial', 'recebido', 'cancelado')),
  forma_pagamento_id bigint references public.formas_pagamento(id),
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (conta_receber_id, numero_parcela)
);

create table if not exists public.recebimentos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id),
  parcela_id bigint not null references public.contas_receber_parcelas(id) on delete cascade,
  data_recebimento timestamptz not null default now(),
  valor numeric(12,2) not null check (valor > 0),
  forma_pagamento_id bigint references public.formas_pagamento(id),
  conta_destino text,
  observacoes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_recebimentos_data
  on public.recebimentos (empresa_id, data_recebimento desc);

-- Fluxo de caixa (entradas por recebimento + saidas por despesas pagas)
create or replace view public.vw_fluxo_caixa as
select
  r.empresa_id,
  r.data_recebimento as data_movimento,
  'entrada'::text as tipo_movimento,
  r.valor as valor,
  'recebimento'::text as origem,
  r.id as origem_id,
  cr.id as conta_receber_id,
  dv.id as documento_id,
  dv.tipo_documento,
  fp.nome as forma_pagamento,
  r.observacoes
from public.recebimentos r
join public.contas_receber_parcelas p on p.id = r.parcela_id
join public.contas_receber cr on cr.id = p.conta_receber_id
left join public.documentos_venda dv on dv.id = cr.documento_id
left join public.formas_pagamento fp on fp.id = coalesce(r.forma_pagamento_id, p.forma_pagamento_id)

union all

select
  d.empresa_id,
  d.data_despesa as data_movimento,
  'saida'::text as tipo_movimento,
  d.valor as valor,
  'despesa'::text as origem,
  d.id as origem_id,
  null::bigint as conta_receber_id,
  null::bigint as documento_id,
  null::text as tipo_documento,
  null::text as forma_pagamento,
  d.descricao as observacoes
from public.despesas d
where d.status = 'pago';

-- =====================
-- RLS + Policies
-- =====================

alter table public.vendas_import_raw enable row level security;
alter table public.documentos_venda enable row level security;
alter table public.documento_venda_itens enable row level security;
alter table public.formas_pagamento enable row level security;
alter table public.contas_receber enable row level security;
alter table public.contas_receber_parcelas enable row level security;
alter table public.recebimentos enable row level security;

drop policy if exists vendas_import_raw_tenant on public.vendas_import_raw;
create policy vendas_import_raw_tenant
on public.vendas_import_raw
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists documentos_venda_tenant on public.documentos_venda;
create policy documentos_venda_tenant
on public.documentos_venda
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists documento_venda_itens_tenant on public.documento_venda_itens;
create policy documento_venda_itens_tenant
on public.documento_venda_itens
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists formas_pagamento_tenant on public.formas_pagamento;
create policy formas_pagamento_tenant
on public.formas_pagamento
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists contas_receber_tenant on public.contas_receber;
create policy contas_receber_tenant
on public.contas_receber
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists contas_receber_parcelas_tenant on public.contas_receber_parcelas;
create policy contas_receber_parcelas_tenant
on public.contas_receber_parcelas
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists recebimentos_tenant on public.recebimentos;
create policy recebimentos_tenant
on public.recebimentos
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

-- Platform admin com acesso total

drop policy if exists vendas_import_raw_platform_admin on public.vendas_import_raw;
create policy vendas_import_raw_platform_admin
on public.vendas_import_raw
for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists documentos_venda_platform_admin on public.documentos_venda;
create policy documentos_venda_platform_admin
on public.documentos_venda
for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists documento_venda_itens_platform_admin on public.documento_venda_itens;
create policy documento_venda_itens_platform_admin
on public.documento_venda_itens
for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists formas_pagamento_platform_admin on public.formas_pagamento;
create policy formas_pagamento_platform_admin
on public.formas_pagamento
for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists contas_receber_platform_admin on public.contas_receber;
create policy contas_receber_platform_admin
on public.contas_receber
for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists contas_receber_parcelas_platform_admin on public.contas_receber_parcelas;
create policy contas_receber_parcelas_platform_admin
on public.contas_receber_parcelas
for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists recebimentos_platform_admin on public.recebimentos;
create policy recebimentos_platform_admin
on public.recebimentos
for all
using (public.is_platform_admin())
with check (public.is_platform_admin());
