-- Setup de staging para importacao de itens (rodar 1x)
create table if not exists public.vendas_itens_import_raw (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id),
  lote_ref text not null,
  source_row_num integer,
  source_item_id text,
  pedido_legacy_id_raw text,
  tipo_venda_raw text,
  produto_legacy_id_raw text,
  produto_nome_raw text,
  quantidade_raw text,
  valor_unitario_raw text,
  total_raw text,
  margem_raw text,
  custo_unitario_raw text,
  custo_total_raw text,
  qtd_disponivel_raw text,
  payload jsonb,
  created_at timestamptz not null default now(),
  unique (empresa_id, source_item_id)
);

alter table public.vendas_itens_import_raw enable row level security;

drop policy if exists vendas_itens_import_raw_tenant on public.vendas_itens_import_raw;
create policy vendas_itens_import_raw_tenant
on public.vendas_itens_import_raw
for all
using (public.user_belongs_to_empresa(empresa_id))
with check (public.user_belongs_to_empresa(empresa_id));

drop policy if exists vendas_itens_import_raw_platform_admin on public.vendas_itens_import_raw;
create policy vendas_itens_import_raw_platform_admin
on public.vendas_itens_import_raw
for all
using (public.is_platform_admin())
with check (public.is_platform_admin());
